### ISSUE TITLE
config.yaml File Not Found

### ISSUE THREAD

**Issue by miragessee** [XHwind/V2XP-ASG#3]
Hello,

I encounter the following error when trying to run the V2XP-ASG project:
```

(opencood) hakan@hakanubuntu:~/V2XP-ASG$ ./run_sg.sh
Running Intermediate Fusion
INFO - 2024-02-11 23:36:57,918 - utils - NumExpr defaulting to 6 threads.
Traceback (most recent call last):
  File "/home/hakan/anaconda3/envs/opencood/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hakan/anaconda3/envs/opencood/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hakan/V2XP-ASG/asg/scripts/scene_generator.py", line 110, in <module>
    generate_adversarial_scenes(opt)
  File "/home/hakan/V2XP-ASG/asg/scripts/scene_generator.py", line 20, in generate_adversarial_scenes
    attack_model = build_adversarial_model(opt, scene_params["adversarial"])
  File "/home/hakan/V2XP-ASG/asg/core/adversarial_optimization/__init__.py", line 23, in build_adversarial_model
    adversarial_model = __all__[adversarial_model_name](opt,
  File "/home/hakan/V2XP-ASG/asg/core/adversarial_optimization/genetic_algorithm.py", line 24, in __init__
    super(GeneticAlgorithm, self).__init__(opt, config)
  File "/home/hakan/V2XP-ASG/asg/core/adversarial_optimization/base_adversarial.py", line 87, in __init__
    self.model_params = load_yaml(None, opt)
  File "/home/hakan/V2XP-ASG/opencood/hypes_yaml/yaml_utils.py", line 28, in load_yaml
    stream = open(file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/hakan/V2XP-ASG/opencood/logs/model_dir/config.yaml'
```

How can I resolve this issue? Could you please provide information about where the required `config.yaml` file should be located or how to create this file?

Thank you.

**Comment by XHwind** [comment]
The `config.yaml` is the configuration file for the cooperative perception models. You will need to train the V2X model beforehand to generate the model metadata (e.g., ckpt and config file) within the `V2XP-ASG/opencood/logs` folder. To do so, you can refer to [OpenCOOD](https://github.com/DerrickXuNu/OpenCOOD) for training the models.
